name: gateway_ci

# 이 워크플로우는 PR이 열리거나 커밋이 push될 때 실행됩니다.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소에서 소스 코드를 체크아웃합니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 환경을 설정합니다. (Java 버전 변경 가능)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      # 3. 종속성을 설치하고 테스트를 실행합니다.
      - name: Build with Gradle
        run: ./gradlew clean build

      # 4. 테스트 결과를 GitHub Actions에 보고합니다.
      - name: Run tests
        run: ./gradlew test

      # 5. 테스트 결과를 저장합니다. (성공, 실패 모두)
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
