name: Configure Secrets

on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Configure environment variables
        run: |
          echo "EUREKA_SERVER_HOSTNAME=${{ secrets.EUREKA_SERVER_HOSTNAME }}" >> $GITHUB_ENV
          echo "EUREKA_SERVER_PORT=${{ secrets.EUREKA_SERVER_PORT }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
        env:
          EUREKA_SERVER_HOSTNAME: ${{ secrets.EUREKA_SERVER_HOSTNAME }}
          EUREKA_SERVER_PORT: ${{ secrets.EUREKA_SERVER_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Print environment variables
        run: |
          echo "EUREKA_SERVER_HOSTNAME=$EUREKA_SERVER_HOSTNAME"
          echo "EUREKA_SERVER_PORT=$EUREKA_SERVER_PORT"
          echo "JWT_SECRET=$JWT_SECRET"